steps:
  # Шаг 1: Сборка Docker-образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bambu-service-bot/telegram-bot:$COMMIT_SHA', '.']

  # Шаг 2: Загрузка Docker-образа в Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bambu-service-bot/telegram-bot:$COMMIT_SHA']

  # Шаг 3: Деплой в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'telegram-bot',
           '--image', 'gcr.io/bambu-service-bot/telegram-bot:$COMMIT_SHA',
           '--platform', 'managed',
           '--region', 'europe-west1',
           '--allow-unauthenticated',
           '--timeout', '300']
options:
  logging: CLOUD_LOGGING_ONLY  # Используем только Cloud Logging
